name: Build and Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-docs.yml
    with:
      docit-path: .
    permissions:
      contents: write
      pages: write
      id-token: write
